/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 * @author aagranda
 */
public class HerramientasAdministrativas extends javax.swing.JFrame {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bmAcerca;
    private javax.swing.JMenu bmActualizar;
    private javax.swing.JMenuItem bmActualizarInformacionCuenta;
    private javax.swing.JMenuItem bmActualizarRegistroCliente;
    private javax.swing.JMenuItem bmAyuda;
    private javax.swing.JMenu bmBorrar;
    private javax.swing.JMenuItem bmBorrarCliente;
    private javax.swing.JMenuItem bmBorrarCuenta;
    private javax.swing.JMenuBar bmMenu;
    private javax.swing.JMenu bmRegistrar;
    private javax.swing.JMenuItem bmRegistrarCliente;
    private javax.swing.JMenuItem bmRegistrarCuenta;
    private javax.swing.JMenuItem bmSalir;
    private javax.swing.JMenu bmSistema;
    private javax.swing.JMenuItem bmVerClientesRegistrados;
    private javax.swing.JMenuItem bmVerCuentasCreadas;
    private javax.swing.JMenu bmVisualizar;
    private javax.swing.JButton btActualizarRegistroCliente;
    private javax.swing.JButton btActualizarRegistroCuenta;
    private javax.swing.JButton btBorrarCliente;
    private javax.swing.JButton btBorrarCuenta;
    private javax.swing.JButton btRegistrarCliente;
    private javax.swing.JButton btRegistrarCuenta;
    private javax.swing.JButton btVisualizarClientesRegistrados;
    private javax.swing.JButton btVisualizarCuentasCreadas;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JPanel jPanel1;
    /**
     * Creates new form HerramientasAdministrativas
     */
    public HerramientasAdministrativas() {
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HerramientasAdministrativas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HerramientasAdministrativas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HerramientasAdministrativas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HerramientasAdministrativas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HerramientasAdministrativas().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btRegistrarCliente = new javax.swing.JButton();
        btRegistrarCuenta = new javax.swing.JButton();
        btActualizarRegistroCliente = new javax.swing.JButton();
        btActualizarRegistroCuenta = new javax.swing.JButton();
        btBorrarCliente = new javax.swing.JButton();
        btBorrarCuenta = new javax.swing.JButton();
        btVisualizarCuentasCreadas = new javax.swing.JButton();
        btVisualizarClientesRegistrados = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        bmMenu = new javax.swing.JMenuBar();
        bmRegistrar = new javax.swing.JMenu();
        bmRegistrarCliente = new javax.swing.JMenuItem();
        bmRegistrarCuenta = new javax.swing.JMenuItem();
        bmActualizar = new javax.swing.JMenu();
        bmActualizarRegistroCliente = new javax.swing.JMenuItem();
        bmActualizarInformacionCuenta = new javax.swing.JMenuItem();
        bmBorrar = new javax.swing.JMenu();
        bmBorrarCliente = new javax.swing.JMenuItem();
        bmBorrarCuenta = new javax.swing.JMenuItem();
        bmVisualizar = new javax.swing.JMenu();
        bmVerCuentasCreadas = new javax.swing.JMenuItem();
        bmVerClientesRegistrados = new javax.swing.JMenuItem();
        bmSistema = new javax.swing.JMenu();
        bmAyuda = new javax.swing.JMenuItem();
        bmAcerca = new javax.swing.JMenuItem();
        bmSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Herramientas Administrativas");

        jPanel1.setBackground(new java.awt.Color(0, 110, 80));

        btRegistrarCliente.setBackground(new java.awt.Color(156, 150, 157));
        btRegistrarCliente.setText("Registrar Cliente");
        btRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarClienteActionPerformed(evt);
            }
        });

        btRegistrarCuenta.setBackground(new java.awt.Color(156, 150, 157));
        btRegistrarCuenta.setText("Registrar Cuenta");
        btRegistrarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarCuentaActionPerformed(evt);
            }
        });

        btActualizarRegistroCliente.setBackground(new java.awt.Color(156, 150, 157));
        btActualizarRegistroCliente.setText("Actualizar Registro de Cliente");

        btActualizarRegistroCuenta.setBackground(new java.awt.Color(156, 150, 157));
        btActualizarRegistroCuenta.setText("Actualizar Informacio de Cuenta");

        btBorrarCliente.setBackground(new java.awt.Color(156, 150, 157));
        btBorrarCliente.setText("Borrar Cliente");

        btBorrarCuenta.setBackground(new java.awt.Color(156, 150, 157));
        btBorrarCuenta.setText("Borrar Cuenta");

        btVisualizarCuentasCreadas.setBackground(new java.awt.Color(156, 150, 157));
        btVisualizarCuentasCreadas.setText("Visualizar Cuentas Creadas");

        btVisualizarClientesRegistrados.setBackground(new java.awt.Color(156, 150, 157));
        btVisualizarClientesRegistrados.setText("Visualizar Clientes Registrados");

        jDesktopPane2.setBackground(new java.awt.Color(204, 255, 204));
        jDesktopPane2.setForeground(new java.awt.Color(0, 110, 80));

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
                jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
                jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 396, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(btRegistrarCliente)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(btRegistrarCuenta)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(btActualizarRegistroCliente)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(btActualizarRegistroCuenta))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(30, 30, 30)
                                                                .addComponent(btBorrarCliente)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(btBorrarCuenta)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(btVisualizarCuentasCreadas)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(btVisualizarClientesRegistrados)))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jDesktopPane2)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btRegistrarCliente)
                                        .addComponent(btRegistrarCuenta)
                                        .addComponent(btActualizarRegistroCliente)
                                        .addComponent(btActualizarRegistroCuenta))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btBorrarCliente)
                                        .addComponent(btBorrarCuenta)
                                        .addComponent(btVisualizarCuentasCreadas)
                                        .addComponent(btVisualizarClientesRegistrados))
                                .addGap(18, 18, 18)
                                .addComponent(jDesktopPane2)
                                .addContainerGap())
        );

        bmMenu.setBackground(new java.awt.Color(10, 69, 53));

        bmRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        bmRegistrar.setText("Registrar");

        bmRegistrarCliente.setText("Registrar Cliente");
        bmRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmRegistrarClienteActionPerformed(evt);
            }
        });
        bmRegistrar.add(bmRegistrarCliente);

        bmRegistrarCuenta.setText("Registrar Cuenta");
        bmRegistrarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmRegistrarCuentaActionPerformed(evt);
            }
        });
        bmRegistrar.add(bmRegistrarCuenta);

        bmMenu.add(bmRegistrar);

        bmActualizar.setForeground(new java.awt.Color(255, 255, 255));
        bmActualizar.setText("Actualizar");

        bmActualizarRegistroCliente.setText("Actualizar Registro de Cliente");
        bmActualizar.add(bmActualizarRegistroCliente);

        bmActualizarInformacionCuenta.setText("Actualizar Informacion de Cuenta");
        bmActualizar.add(bmActualizarInformacionCuenta);

        bmMenu.add(bmActualizar);

        bmBorrar.setForeground(new java.awt.Color(255, 255, 255));
        bmBorrar.setText("Borrar");

        bmBorrarCliente.setText("Borrar Cliente");
        bmBorrar.add(bmBorrarCliente);

        bmBorrarCuenta.setText("Borrar Cuenta");
        bmBorrar.add(bmBorrarCuenta);

        bmMenu.add(bmBorrar);

        bmVisualizar.setForeground(new java.awt.Color(255, 255, 255));
        bmVisualizar.setText("Visualizacion");

        bmVerCuentasCreadas.setText("Ver Cuentas Creadas");
        bmVisualizar.add(bmVerCuentasCreadas);

        bmVerClientesRegistrados.setText("Ver Clientes Registrados");
        bmVisualizar.add(bmVerClientesRegistrados);

        bmMenu.add(bmVisualizar);

        bmSistema.setForeground(new java.awt.Color(255, 255, 255));
        bmSistema.setText("Sistema");

        bmAyuda.setText("Ayuda");
        bmSistema.add(bmAyuda);

        bmAcerca.setText("Acerca de...");
        bmSistema.add(bmAcerca);

        bmSalir.setText("Salir");
        bmSistema.add(bmSalir);

        bmMenu.add(bmSistema);

        setJMenuBar(bmMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarClienteActionPerformed
        Formularios.RegistrarCliente cc = new RegistrarCliente();
        jDesktopPane2.add(cc);
        cc.setVisible(true);
    }//GEN-LAST:event_btRegistrarClienteActionPerformed

    private void btRegistrarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarCuentaActionPerformed
        Formularios.RegistrarCuenta cc = new RegistrarCuenta();
        cc.setVisible(true);
    }//GEN-LAST:event_btRegistrarCuentaActionPerformed

    private void bmRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmRegistrarClienteActionPerformed
        Formularios.RegistrarCliente cc = new RegistrarCliente();
        jDesktopPane2.add(cc);
        cc.setVisible(true);
    }//GEN-LAST:event_bmRegistrarClienteActionPerformed

    private void bmRegistrarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmRegistrarCuentaActionPerformed
        Formularios.RegistrarCuenta cc = new RegistrarCuenta();
        cc.setVisible(true);
    }//GEN-LAST:event_bmRegistrarCuentaActionPerformed
    // End of variables declaration//GEN-END:variables
}
