/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 * @author aagranda
 */
public class Menu extends javax.swing.JFrame {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenuItem bmAcerca;
    private javax.swing.JMenu bmAdministrativo;
    private javax.swing.JMenuItem bmAyuda;
    private javax.swing.JMenuItem bmRegistrar;
    private javax.swing.JMenuItem bmSalir;
    private javax.swing.JMenu bmSistema;
    private javax.swing.JButton btAccesoAdministrativo;
    private javax.swing.JButton btAccesoCliente;
    private javax.swing.JPanel jPanel1;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btAccesoAdministrativo = new javax.swing.JButton();
        btAccesoCliente = new javax.swing.JButton();
        BarraMenu = new javax.swing.JMenuBar();
        bmAdministrativo = new javax.swing.JMenu();
        bmRegistrar = new javax.swing.JMenuItem();
        bmSistema = new javax.swing.JMenu();
        bmAyuda = new javax.swing.JMenuItem();
        bmAcerca = new javax.swing.JMenuItem();
        bmSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BANCO GRANDA CORP.");
        setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        btAccesoAdministrativo.setBackground(new java.awt.Color(156, 150, 157));
        btAccesoAdministrativo.setText("Acceso Administrativo");
        btAccesoAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAccesoAdministrativoActionPerformed(evt);
            }
        });

        btAccesoCliente.setBackground(new java.awt.Color(156, 150, 157));
        btAccesoCliente.setText("Acceso Cliente");
        btAccesoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAccesoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(btAccesoAdministrativo)
                                .addGap(96, 96, 96)
                                .addComponent(btAccesoCliente)
                                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btAccesoAdministrativo)
                                        .addComponent(btAccesoCliente))
                                .addContainerGap(255, Short.MAX_VALUE))
        );

        BarraMenu.setBackground(new java.awt.Color(10, 69, 53));
        BarraMenu.setBorder(null);

        bmAdministrativo.setForeground(new java.awt.Color(255, 255, 255));
        bmAdministrativo.setText("Administrativo");

        bmRegistrar.setText("Herramientas Administrativas");
        bmAdministrativo.add(bmRegistrar);

        BarraMenu.add(bmAdministrativo);

        bmSistema.setForeground(new java.awt.Color(255, 255, 255));
        bmSistema.setText("Sistema");

        bmAyuda.setText("Ayuda");
        bmAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmAyudaActionPerformed(evt);
            }
        });
        bmSistema.add(bmAyuda);

        bmAcerca.setText("Acerca de...");
        bmSistema.add(bmAcerca);

        bmSalir.setText("Salir");
        bmSistema.add(bmSalir);

        BarraMenu.add(bmSistema);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAccesoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAccesoClienteActionPerformed
        Formularios.LoginCliente lc = new Formularios.LoginCliente();
        lc.setVisible(true);
    }//GEN-LAST:event_btAccesoClienteActionPerformed

    private void btAccesoAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAccesoAdministrativoActionPerformed
        Formularios.Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btAccesoAdministrativoActionPerformed

    private void bmAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bmAyudaActionPerformed
    // End of variables declaration//GEN-END:variables
}
